language: node_js
node_js:
  - "8.0.0"
  
services:
  - postgresql

addons:
    postgresql: '9.6'


env:
  - DATABASE_URL='postgres://codex:codex123@localhost:5432/GreetingsApp';


before_script:
  - psql -c 'create database  GreetingsApp;' -U postgres
  - psql -c 'create user codex WITH PASSWORD 'codex123';' -U postgres
  # - psql -U postgres -d GreetingsApp -a -f tables.sql