language: node_js
node_js:
  - "8.0.0"
  
Services:
  - postgresql

addons:
    postgresql: '9.6'


env:
  - DATABASE_URL='postgresql://postgresql@localhost:5432/GreetingsApp';


before_script:
  - psql -c 'create database  GreetingsApp;' -U postgres
  # - psql -U postgres -d GreetingsApp -a -f tables.sql